spring.application.name=api-cadastro-cliente
spring.datasource.url=jdbc:mysql://localhost:3306/cadastro_clientes?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=kessyjohne257
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true